config/routes.rb
Rails.application.routes.draw do
  resources :trabajos
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "trabajos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/postulacion.rb
class Postulacion < ApplicationRecord
  belongs_to :user
  belongs_to :trabajo
end

app/models/trabajo.rb
class Trabajo < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone])
      devise_parameter_sanitizer.permit(:account_uptade, keys: [:name, :phone])
    end
  end

app/controllers/trabajos_controller.rb
class TrabajosController < ApplicationController
  before_action :set_trabajo, only: %i[ show edit update destroy ]

  # GET /trabajos or /trabajos.json
  def index
    @trabajos = Trabajo.all
  end

  # GET /trabajos/1 or /trabajos/1.json
  def show
  end

  # GET /trabajos/new
  def new
    @trabajo = Trabajo.new
  end

  # GET /trabajos/1/edit
  def edit
  end

  # POST /trabajos or /trabajos.json
  def create
    @trabajo = Trabajo.new(trabajo_params)

    respond_to do |format|
      if @trabajo.save
        format.html { redirect_to trabajo_url(@trabajo), notice: "Trabajo was successfully created." }
        format.json { render :show, status: :created, location: @trabajo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trabajo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trabajos/1 or /trabajos/1.json
  def update
    respond_to do |format|
      if @trabajo.update(trabajo_params)
        format.html { redirect_to trabajo_url(@trabajo), notice: "Trabajo was successfully updated." }
        format.json { render :show, status: :ok, location: @trabajo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trabajo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trabajos/1 or /trabajos/1.json
  def destroy
    @trabajo.destroy

    respond_to do |format|
      format.html { redirect_to trabajos_url, notice: "Trabajo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trabajo
      @trabajo = Trabajo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trabajo_params
      params.require(:trabajo).permit(:cargo, :area, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trabajos_helper.rb
module TrabajosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NuevoTrabajo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>



    
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/trabajos/_form.html.erb
<%= form_with(model: trabajo) do |form| %>
  <% if trabajo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trabajo.errors.count, "error") %> prohibited this trabajo from being saved:</h2>

      <ul>
        <% trabajo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cargo, style: "display: block" %>
    <%= form.text_field :cargo %>
  </div>

  <div>
    <%= form.label :area, style: "display: block" %>
    <%= form.text_field :area %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trabajos/_trabajo.html.erb
<div id="<%= dom_id trabajo %>">
  <p>
    <strong>Cargo:</strong>
    <%= trabajo.cargo %>
  </p>

  <p>
    <strong>Area:</strong>
    <%= trabajo.area %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= trabajo.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= trabajo.user_id %>
  </p>

</div>

app/views/trabajos/edit.html.erb
<h1>Editing trabajo</h1>

<%= render "form", trabajo: @trabajo %>

<br>

<div>
  <%= link_to "Show this trabajo", @trabajo %> |
  <%= link_to "Back to trabajos", trabajos_path %>
</div>

app/views/trabajos/index.html.erb
<p style="color: green"><%= notice %></p>
<section class="container">

<h1>Trabajos</h1>

<div id="trabajos">
  <% @trabajos.each do |trabajo| %>
    <%= render trabajo %>
    <p>
      <%= link_to "Show this trabajo", trabajo %>
    </p>
  <% end %>
</div>

<%= link_to "New trabajo", new_trabajo_path %>

</section>

app/views/trabajos/new.html.erb
<h1>New trabajo</h1>

<%= render "form", trabajo: @trabajo %>

<br>

<div>
  <%= link_to "Back to trabajos", trabajos_path %>
</div>

app/views/trabajos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @trabajo %>

<div>
  <%= link_to "Edit this trabajo", edit_trabajo_path(@trabajo) %> |
  <%= link_to "Back to trabajos", trabajos_path %>

  <%= button_to "Destroy this trabajo", @trabajo, method: :delete %>
</div>